/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * AsyncUpdateResponse
 */

public class AsyncUpdateResponse {
  @JsonProperty("approvedVINs")
  private List<String> approvedVINs = null;

  @JsonProperty("consentRequestAsyncUpdateInfoUrl")
  private String consentRequestAsyncUpdateInfoUrl;

  public AsyncUpdateResponse approvedVINs(List<String> approvedVINs) {
    this.approvedVINs = approvedVINs;
    return this;
  }

  public AsyncUpdateResponse addApprovedVINsItem(String approvedVINsItem) {
    if (this.approvedVINs == null) {
      this.approvedVINs = new ArrayList<>();
    }
    this.approvedVINs.add(approvedVINsItem);
    return this;
  }

   /**
   * List approved VINs that were not deleted. This property is only shown for removeNonApprovedVINsAsync endpoint
   * @return approvedVINs
  **/
  @ApiModelProperty(value = "List approved VINs that were not deleted. This property is only shown for removeNonApprovedVINsAsync endpoint")
  public List<String> getApprovedVINs() {
    return approvedVINs;
  }

  public void setApprovedVINs(List<String> approvedVINs) {
    this.approvedVINs = approvedVINs;
  }

  public AsyncUpdateResponse consentRequestAsyncUpdateInfoUrl(String consentRequestAsyncUpdateInfoUrl) {
    this.consentRequestAsyncUpdateInfoUrl = consentRequestAsyncUpdateInfoUrl;
    return this;
  }

   /**
   * Url to get detailed information of consent request async update
   * @return consentRequestAsyncUpdateInfoUrl
  **/
  @ApiModelProperty(value = "Url to get detailed information of consent request async update")
  public String getConsentRequestAsyncUpdateInfoUrl() {
    return consentRequestAsyncUpdateInfoUrl;
  }

  public void setConsentRequestAsyncUpdateInfoUrl(String consentRequestAsyncUpdateInfoUrl) {
    this.consentRequestAsyncUpdateInfoUrl = consentRequestAsyncUpdateInfoUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AsyncUpdateResponse asyncUpdateResponse = (AsyncUpdateResponse) o;
    return Objects.equals(this.approvedVINs, asyncUpdateResponse.approvedVINs) &&
        Objects.equals(this.consentRequestAsyncUpdateInfoUrl, asyncUpdateResponse.consentRequestAsyncUpdateInfoUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approvedVINs, consentRequestAsyncUpdateInfoUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AsyncUpdateResponse {\n");
    
    sb.append("    approvedVINs: ").append(toIndentedString(approvedVINs)).append("\n");
    sb.append("    consentRequestAsyncUpdateInfoUrl: ").append(toIndentedString(consentRequestAsyncUpdateInfoUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

