/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;


/**
 * Consumer
 */

public class Consumer {
  @JsonProperty("clientId")
  private String clientId;

  @JsonProperty("clientSecret")
  private String clientSecret;

  @JsonProperty("consumerId")
  private String consumerId;

  @JsonProperty("consumerName")
  private String consumerName;

  @JsonProperty("openIdAuthUrl")
  private String openIdAuthUrl;

  @JsonProperty("openIdTokenUrl")
  private String openIdTokenUrl;

  @JsonProperty("responseType")
  private String responseType;

  public Consumer clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * ID of registered on consumer OAuth service HERE client
   * @return clientId
  **/
  @ApiModelProperty(value = "ID of registered on consumer OAuth service HERE client")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public Consumer clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Secret of registered on consumer Oauth service HERE client
   * @return clientSecret
  **/
  @ApiModelProperty(value = "Secret of registered on consumer Oauth service HERE client")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public Consumer consumerId(String consumerId) {
    this.consumerId = consumerId;
    return this;
  }

   /**
   * Consumer identifier on Marketplace
   * @return consumerId
  **/
  @ApiModelProperty(example = "olp-consumer-example", value = "Consumer identifier on Marketplace")
  public String getConsumerId() {
    return consumerId;
  }

  public void setConsumerId(String consumerId) {
    this.consumerId = consumerId;
  }

  public Consumer consumerName(String consumerName) {
    this.consumerName = consumerName;
    return this;
  }

   /**
   * Consumer name on Marketplace
   * @return consumerName
  **/
  @ApiModelProperty(example = "Ensure", value = "Consumer name on Marketplace")
  public String getConsumerName() {
    return consumerName;
  }

  public void setConsumerName(String consumerName) {
    this.consumerName = consumerName;
  }

  public Consumer openIdAuthUrl(String openIdAuthUrl) {
    this.openIdAuthUrl = openIdAuthUrl;
    return this;
  }

   /**
   * Consumers OAuth login service url
   * @return openIdAuthUrl
  **/
  @ApiModelProperty(example = "https://consumer/oauth2/auth", value = "Consumers OAuth login service url")
  public String getOpenIdAuthUrl() {
    return openIdAuthUrl;
  }

  public void setOpenIdAuthUrl(String openIdAuthUrl) {
    this.openIdAuthUrl = openIdAuthUrl;
  }

  public Consumer openIdTokenUrl(String openIdTokenUrl) {
    this.openIdTokenUrl = openIdTokenUrl;
    return this;
  }

   /**
   * Consumers OAuth token service url
   * @return openIdTokenUrl
  **/
  @ApiModelProperty(example = "https://consumer/oauth2/token", value = "Consumers OAuth token service url")
  public String getOpenIdTokenUrl() {
    return openIdTokenUrl;
  }

  public void setOpenIdTokenUrl(String openIdTokenUrl) {
    this.openIdTokenUrl = openIdTokenUrl;
  }

  public Consumer responseType(String responseType) {
    this.responseType = responseType;
    return this;
  }

   /**
   * Response type
   * @return responseType
  **/
  @ApiModelProperty(example = "code", value = "Response type")
  public String getResponseType() {
    return responseType;
  }

  public void setResponseType(String responseType) {
    this.responseType = responseType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Consumer consumer = (Consumer) o;
    return Objects.equals(this.clientId, consumer.clientId) &&
        Objects.equals(this.clientSecret, consumer.clientSecret) &&
        Objects.equals(this.consumerId, consumer.consumerId) &&
        Objects.equals(this.consumerName, consumer.consumerName) &&
        Objects.equals(this.openIdAuthUrl, consumer.openIdAuthUrl) &&
        Objects.equals(this.openIdTokenUrl, consumer.openIdTokenUrl) &&
        Objects.equals(this.responseType, consumer.responseType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, clientSecret, consumerId, consumerName, openIdAuthUrl, openIdTokenUrl, responseType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Consumer {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    consumerId: ").append(toIndentedString(consumerId)).append("\n");
    sb.append("    consumerName: ").append(toIndentedString(consumerName)).append("\n");
    sb.append("    openIdAuthUrl: ").append(toIndentedString(openIdAuthUrl)).append("\n");
    sb.append("    openIdTokenUrl: ").append(toIndentedString(openIdTokenUrl)).append("\n");
    sb.append("    responseType: ").append(toIndentedString(responseType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

