/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;


/**
 * ConsentStatus
 */

public class ConsentStatus {
  @JsonProperty("consentRequestId")
  private String consentRequestId;

  @JsonProperty("state")
  private String state;

  @JsonProperty("vin")
  private String vin;

  public ConsentStatus consentRequestId(String consentRequestId) {
    this.consentRequestId = consentRequestId;
    return this;
  }

   /**
   * ID of consent request
   * @return consentRequestId
  **/
  @ApiModelProperty(value = "ID of consent request")
  public String getConsentRequestId() {
    return consentRequestId;
  }

  public void setConsentRequestId(String consentRequestId) {
    this.consentRequestId = consentRequestId;
  }

  public ConsentStatus state(String state) {
    this.state = state;
    return this;
  }

   /**
   * State of consent
   * @return state
  **/
  @ApiModelProperty(example = "PENDING", value = "State of consent")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public ConsentStatus vin(String vin) {
    this.vin = vin;
    return this;
  }

   /**
   * Vehicle ID
   * @return vin
  **/
  @ApiModelProperty(value = "Vehicle ID")
  public String getVin() {
    return vin;
  }

  public void setVin(String vin) {
    this.vin = vin;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentStatus consentStatus = (ConsentStatus) o;
    return Objects.equals(this.consentRequestId, consentStatus.consentRequestId) &&
        Objects.equals(this.state, consentStatus.state) &&
        Objects.equals(this.vin, consentStatus.vin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consentRequestId, state, vin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentStatus {\n");
    
    sb.append("    consentRequestId: ").append(toIndentedString(consentRequestId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    vin: ").append(toIndentedString(vin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

