/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;


/**
 * Response in case of error
 */
@ApiModel(description = "Response in case of error")

public class ErrorResponse {
  @JsonProperty("action")
  private String action;

  @JsonProperty("cause")
  private String cause;

  @JsonProperty("code")
  private String code;

  @JsonProperty("correlationId")
  private String correlationId;

  @JsonProperty("status")
  private Integer status;

  @JsonProperty("title")
  private String title;

  public ErrorResponse action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Actions that could be done to deal with the error
   * @return action
  **/
  @ApiModelProperty(required = true, value = "Actions that could be done to deal with the error")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public ErrorResponse cause(String cause) {
    this.cause = cause;
    return this;
  }

   /**
   * Cause of the error
   * @return cause
  **/
  @ApiModelProperty(required = true, value = "Cause of the error")
  public String getCause() {
    return cause;
  }

  public void setCause(String cause) {
    this.cause = cause;
  }

  public ErrorResponse code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Error code
   * @return code
  **/
  @ApiModelProperty(example = "E602101", required = true, value = "Error code")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ErrorResponse correlationId(String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

   /**
   * Auto generated identifier of the request
   * @return correlationId
  **/
  @ApiModelProperty(required = true, value = "Auto generated identifier of the request")
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }

  public ErrorResponse status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * HTTP status code of the error
   * @return status
  **/
  @ApiModelProperty(required = true, value = "HTTP status code of the error")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public ErrorResponse title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title of the error
   * @return title
  **/
  @ApiModelProperty(required = true, value = "Title of the error")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponse errorResponse = (ErrorResponse) o;
    return Objects.equals(this.action, errorResponse.action) &&
        Objects.equals(this.cause, errorResponse.cause) &&
        Objects.equals(this.code, errorResponse.code) &&
        Objects.equals(this.correlationId, errorResponse.correlationId) &&
        Objects.equals(this.status, errorResponse.status) &&
        Objects.equals(this.title, errorResponse.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, cause, code, correlationId, status, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorResponse {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    cause: ").append(toIndentedString(cause)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

