/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;


/**
 * ProviderApplication
 */

public class ProviderApplication {
  @JsonProperty("clientId")
  private String clientId;

  @JsonProperty("clientSecret")
  private String clientSecret;

  @JsonProperty("consumerId")
  private String consumerId;

  @JsonProperty("containerId")
  private String containerId;

  @JsonProperty("providerId")
  private String providerId;

  @JsonProperty("redirectUri")
  private String redirectUri;

  public ProviderApplication clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Provider application client id to provider service
   * @return clientId
  **/
  @ApiModelProperty(value = "Provider application client id to provider service")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ProviderApplication clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * Provider application client secret to provider service
   * @return clientSecret
  **/
  @ApiModelProperty(value = "Provider application client secret to provider service")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public ProviderApplication consumerId(String consumerId) {
    this.consumerId = consumerId;
    return this;
  }

   /**
   * Consumer realm id
   * @return consumerId
  **/
  @ApiModelProperty(value = "Consumer realm id")
  public String getConsumerId() {
    return consumerId;
  }

  public void setConsumerId(String consumerId) {
    this.consumerId = consumerId;
  }

  public ProviderApplication containerId(String containerId) {
    this.containerId = containerId;
    return this;
  }

   /**
   * Container id
   * @return containerId
  **/
  @ApiModelProperty(value = "Container id")
  public String getContainerId() {
    return containerId;
  }

  public void setContainerId(String containerId) {
    this.containerId = containerId;
  }

  public ProviderApplication providerId(String providerId) {
    this.providerId = providerId;
    return this;
  }

   /**
   * Provider realm id
   * @return providerId
  **/
  @ApiModelProperty(value = "Provider realm id")
  public String getProviderId() {
    return providerId;
  }

  public void setProviderId(String providerId) {
    this.providerId = providerId;
  }

  public ProviderApplication redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * Redirect URI of current provider
   * @return redirectUri
  **/
  @ApiModelProperty(example = "https://redirect.here.com/oauth2/callback", value = "Redirect URI of current provider")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProviderApplication providerApplication = (ProviderApplication) o;
    return Objects.equals(this.clientId, providerApplication.clientId) &&
        Objects.equals(this.clientSecret, providerApplication.clientSecret) &&
        Objects.equals(this.consumerId, providerApplication.consumerId) &&
        Objects.equals(this.containerId, providerApplication.containerId) &&
        Objects.equals(this.providerId, providerApplication.providerId) &&
        Objects.equals(this.redirectUri, providerApplication.redirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, clientSecret, consumerId, containerId, providerId, redirectUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProviderApplication {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    consumerId: ").append(toIndentedString(consumerId)).append("\n");
    sb.append("    containerId: ").append(toIndentedString(containerId)).append("\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

