/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * SoftRemovalDataSubjectsResponse
 */

public class SoftRemovalDataSubjectsResponse {
  @JsonProperty("approvedVINs")
  private List<String> approvedVINs = null;

  @JsonProperty("message")
  private String message;

  public SoftRemovalDataSubjectsResponse approvedVINs(List<String> approvedVINs) {
    this.approvedVINs = approvedVINs;
    return this;
  }

  public SoftRemovalDataSubjectsResponse addApprovedVINsItem(String approvedVINsItem) {
    if (this.approvedVINs == null) {
      this.approvedVINs = new ArrayList<>();
    }
    this.approvedVINs.add(approvedVINsItem);
    return this;
  }

   /**
   * List approved VINs that were not deleted and need to be deleted forcefully
   * @return approvedVINs
  **/
  @ApiModelProperty(value = "List approved VINs that were not deleted and need to be deleted forcefully")
  public List<String> getApprovedVINs() {
    return approvedVINs;
  }

  public void setApprovedVINs(List<String> approvedVINs) {
    this.approvedVINs = approvedVINs;
  }

  public SoftRemovalDataSubjectsResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Message with instructions for further actions
   * @return message
  **/
  @ApiModelProperty(value = "Message with instructions for further actions")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoftRemovalDataSubjectsResponse softRemovalDataSubjectsResponse = (SoftRemovalDataSubjectsResponse) o;
    return Objects.equals(this.approvedVINs, softRemovalDataSubjectsResponse.approvedVINs) &&
        Objects.equals(this.message, softRemovalDataSubjectsResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approvedVINs, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoftRemovalDataSubjectsResponse {\n");
    
    sb.append("    approvedVINs: ").append(toIndentedString(approvedVINs)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

