/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * SuccessApproveData
 */

public class SuccessApproveData {
  @JsonProperty("approvedConsentInfo")
  private ConsentInfo approvedConsentInfo = null;

  @JsonProperty("recentPendingConsentsInfo")
  private List<ConsentInfo> recentPendingConsentsInfo = null;

  public SuccessApproveData approvedConsentInfo(ConsentInfo approvedConsentInfo) {
    this.approvedConsentInfo = approvedConsentInfo;
    return this;
  }

   /**
   * Get approvedConsentInfo
   * @return approvedConsentInfo
  **/
  @ApiModelProperty(value = "")
  public ConsentInfo getApprovedConsentInfo() {
    return approvedConsentInfo;
  }

  public void setApprovedConsentInfo(ConsentInfo approvedConsentInfo) {
    this.approvedConsentInfo = approvedConsentInfo;
  }

  public SuccessApproveData recentPendingConsentsInfo(List<ConsentInfo> recentPendingConsentsInfo) {
    this.recentPendingConsentsInfo = recentPendingConsentsInfo;
    return this;
  }

  public SuccessApproveData addRecentPendingConsentsInfoItem(ConsentInfo recentPendingConsentsInfoItem) {
    if (this.recentPendingConsentsInfo == null) {
      this.recentPendingConsentsInfo = new ArrayList<>();
    }
    this.recentPendingConsentsInfo.add(recentPendingConsentsInfoItem);
    return this;
  }

   /**
   * Information about some of most recent consents in pending state
   * @return recentPendingConsentsInfo
  **/
  @ApiModelProperty(value = "Information about some of most recent consents in pending state")
  public List<ConsentInfo> getRecentPendingConsentsInfo() {
    return recentPendingConsentsInfo;
  }

  public void setRecentPendingConsentsInfo(List<ConsentInfo> recentPendingConsentsInfo) {
    this.recentPendingConsentsInfo = recentPendingConsentsInfo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuccessApproveData successApproveData = (SuccessApproveData) o;
    return Objects.equals(this.approvedConsentInfo, successApproveData.approvedConsentInfo) &&
        Objects.equals(this.recentPendingConsentsInfo, successApproveData.recentPendingConsentsInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approvedConsentInfo, recentPendingConsentsInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuccessApproveData {\n");
    
    sb.append("    approvedConsentInfo: ").append(toIndentedString(approvedConsentInfo)).append("\n");
    sb.append("    recentPendingConsentsInfo: ").append(toIndentedString(recentPendingConsentsInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

