/*
 * HERE Consent Management API v1
 * HERE Consent Management REST API. More details can be found here: https://confluence.in.here.com/display/OLP/Neutral+Server+Consent+Management
 *
 * OpenAPI spec version: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.here.platform.cm.rest.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * UserAccountData
 */

public class UserAccountData {
  @JsonProperty("birthdate")
  private String birthdate;

  @JsonProperty("cm_token")
  private String cmToken;

  @JsonProperty("email")
  private String email;

  @JsonProperty("locale")
  private String locale;

  @JsonProperty("name")
  private String name;

  @JsonProperty("userAccountId")
  private String userAccountId;

  @JsonProperty("vinsData")
  private List<VinData> vinsData = null;

  public UserAccountData birthdate(String birthdate) {
    this.birthdate = birthdate;
    return this;
  }

   /**
   * Birthday date
   * @return birthdate
  **/
  @ApiModelProperty(example = "1992-01-03", value = "Birthday date")
  public String getBirthdate() {
    return birthdate;
  }

  public void setBirthdate(String birthdate) {
    this.birthdate = birthdate;
  }

  public UserAccountData cmToken(String cmToken) {
    this.cmToken = cmToken;
    return this;
  }

   /**
   * CM token
   * @return cmToken
  **/
  @ApiModelProperty(example = "413a0bf6-891e-3648-bf46-72eb399781c0", value = "CM token")
  public String getCmToken() {
    return cmToken;
  }

  public void setCmToken(String cmToken) {
    this.cmToken = cmToken;
  }

  public UserAccountData email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email attached to account
   * @return email
  **/
  @ApiModelProperty(example = "john.smith@gmail.com", value = "Email attached to account")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserAccountData locale(String locale) {
    this.locale = locale;
    return this;
  }

   /**
   * Locale
   * @return locale
  **/
  @ApiModelProperty(example = "en-US", value = "Locale")
  public String getLocale() {
    return locale;
  }

  public void setLocale(String locale) {
    this.locale = locale;
  }

  public UserAccountData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Full name
   * @return name
  **/
  @ApiModelProperty(example = "John Smith", value = "Full name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UserAccountData userAccountId(String userAccountId) {
    this.userAccountId = userAccountId;
    return this;
  }

   /**
   * User account identifier 
   * @return userAccountId
  **/
  @ApiModelProperty(example = "HERE-6f443a6b-c5c7-4517-a02c-309dd4f9176c", value = "User account identifier ")
  public String getUserAccountId() {
    return userAccountId;
  }

  public void setUserAccountId(String userAccountId) {
    this.userAccountId = userAccountId;
  }

  public UserAccountData vinsData(List<VinData> vinsData) {
    this.vinsData = vinsData;
    return this;
  }

  public UserAccountData addVinsDataItem(VinData vinsDataItem) {
    if (this.vinsData == null) {
      this.vinsData = new ArrayList<>();
    }
    this.vinsData.add(vinsDataItem);
    return this;
  }

   /**
   * List of user VINs data
   * @return vinsData
  **/
  @ApiModelProperty(value = "List of user VINs data")
  public List<VinData> getVinsData() {
    return vinsData;
  }

  public void setVinsData(List<VinData> vinsData) {
    this.vinsData = vinsData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAccountData userAccountData = (UserAccountData) o;
    return Objects.equals(this.birthdate, userAccountData.birthdate) &&
        Objects.equals(this.cmToken, userAccountData.cmToken) &&
        Objects.equals(this.email, userAccountData.email) &&
        Objects.equals(this.locale, userAccountData.locale) &&
        Objects.equals(this.name, userAccountData.name) &&
        Objects.equals(this.userAccountId, userAccountData.userAccountId) &&
        Objects.equals(this.vinsData, userAccountData.vinsData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(birthdate, cmToken, email, locale, name, userAccountId, vinsData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAccountData {\n");
    
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    cmToken: ").append(toIndentedString(cmToken)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    userAccountId: ").append(toIndentedString(userAccountId)).append("\n");
    sb.append("    vinsData: ").append(toIndentedString(vinsData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

